application: ploverdojo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /main.html
  script: main.app

- url: /ploverquiz.html
  script: ploverquiz.app

- url: /.*
  script: ploverdojo.app

libraries:
- name: jinja2
  version: latest
